- name: check if bastion host already exists
  virt:
    command: info
  register: virt_info

- name: create bastion host
  block:
  - name: check rhel images exists
    stat:
      path: /root/Downloads/rhel-8.1-x86_64-kvm.qcow2
    register: rhel_qcow

  - fail:
      msg: "please download the rhel image to /root/Downloads/"
    when: not rhel_qcow.stat.exists

  - name: copy rhel image to libvirt folder
    copy:
      src: /root/Downloads/rhel-8.1-x86_64-kvm.qcow2
      dest: /var/lib/libvirt/images/rhel-8.1-x86_64-kvm.qcow2
      remote_src: yes
      force: no

  - name: set root password and remove cloud init
    command: /usr/bin/virt-customize -a /var/lib/libvirt/images/rhel-8.1-x86_64-kvm.qcow2 --root-password password:redhat  --uninstall cloud-init  --hostname bastion --run-command 'mkdir -p /root/.ssh;chmod 700 /root/.ssh; touch /.autorelabel' --copy-in /root/.ssh/authorized_keys:/root/.ssh

  - name: install bastion host with virt-install
    command: virt-install --name bastion --memory 2048 --vcpus 1 --disk /var/lib/libvirt/images/rhel-8.1-x86_64-kvm.qcow2 --import --os-variant rhel8.1 --noautoconsole

  when: virt_info.bastion is not defined
