---
- name: create lab network and hosts
  gather_facts: no
  hosts:
    - playground.stderr.at
  vars:
    network:
      name: lab
      startip: 192.168.100.1
      netmask: 255.255.255.0
    labhosts:
      - name: lab01
        network: lab
        macaddr: "52:54:00:01:50:02"
        ipaddr: "192.168.100.2"
      - name: lab02
        disksize: 100G
        memory: 8192
        cpu: 2
        network: lab
        macaddr: "52:54:00:01:50:03"
        ipaddr: "192.168.100.3"
  roles:
    - lab
