---
- name: install required packages
  dnf:
    name:
      - libvirt
      - podman
      - virt-install
      - virt-manager
      - libguestfs-tools
      - virt-viewer
      - xauth
    state: present

- name: enable and start libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: True
