---
- name: install required packages
  dnf:
    name:
      - libvirt
      - podman
      - virt-install
      - virt-manager
      - libguestfs-tools
      - virt-viewer
      - xauth
      - python3-lxml
    state: present

- name: download required RHCOS files
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/4.3.0/{{ item }}"
    dest: "/root/Downloads/{{ item }}"
  with_items:
    - rhcos-4.3.0-x86_64-metal.raw.gz
    - rhcos-4.3.0-x86_64-installer-initramfs.img
    - rhcos-4.3.0-x86_64-installer-kernel

- name: enable and start libvirtd
  systemd:
    name: libvirtd
    state: started
    enabled: True

- name: define ocp4 network
  virt_net:
    command: define
    autostart: yes
    name: ocp4
    xml: '{{ lookup("template", "templates/network.xml.j2") }}'

- name: start ocp4 network
  virt_net:
    command: create
    name: ocp4

- name: enable autostart for ocp4 network
  virt_net:
    autostart: yes
    name: ocp4
